### PR TITLE
Create pull_request_template.md

### LINKED ISSUE #2: Pull request template
There is no pull request template. I have a fix available in #1

### PR DESCRIPTION
**Pull request by kallangerard**
## Testability

- [x] Implementation can change without breaking tests (black-box tests)
- [x] I can understand the expected behaviour of the system by reading tests
- [x] Uses a variety of testing approaches for robustness (unit + integration etc)
- [x] Has good code coverage and covers a good number of core and edge cases

## Maintainability

- [x] Does the file structure follow a consistent pattern? (e.g. ports and adapters)
- [x] Do file / function / variable / object names reflect their purpose?
- [x] Is there any unnecessary coupling that would make refactoring or testing harder (e.g. email function and sms function linked together)?
- [x] Is the code split into appropriate concerns / layers if necessary. E.g. API code does not interact with database.
- [x] Is there any unnecessary complexity that makes the code harder to reason about?
- [x] Comments provide extra context (the "why?") where necessary
- [x] Is the API, architecture, setup and usage documented (e.g. README, OpenAPI, etc)?
- [x] Is the code configurable? Can you change config in one place without re-factoring?

## Security and privacy

- [x] Are there any opportunities for abuse? E.g. large volume of requests? Bad input?
- [x] Are all entry points authenticated and authorised appropriately?
- [x] Does any process, resource or user have more access than they need?
- [x] Is all PII and sensitive data handled appropriately (not logged, not in plain text, not checked in)
- [x] Are all third-party dependencies vetted and pinned?

## Robustness

- [x] Can you think of any errors or conditions that would cause an unexpected state?
- [x] Are there any statements that won't scale well to large data sets?
- [x] Is there anything that can have an impact on system load / service limits / costs?
- [x] Are all read and write operations logged to assist debugging and support?
- [x] Are error messages readable and assist debugging and support (e.g. shows key non-sensitive details)?

### CODE REVIEW

**Comment by kallangerard** [comment]
@mr-joshcrane please review my pull request

**Comment by t04glovern** [comment]
can I get an ETA on this? we're using the fork in prod

**Comment by kallangerard** [comment]
> can I get an ETA on this? we're using the fork in prod

+1

**Comment by mr-joshcrane** [comment]
Hey I had a few light edits of the original checklist that I feel captures the intent a bit better @kallangerard @t04glovern 

## Unquestionable Testability
- [x] A sublime capability for modification sans deterrent impact on tests (an exquisite black-box-test mastery)
- [x] A breathtaking clarity concerning system behavior emanates from the very essence of the tests
- [x] Utilizing a multitudinous array of testing techniques, ensuring uncompromising robustness (the intricacies of unit + integration encompassed within)
- [x] Magnificent code coverage obtained, encompassing a vast realm of paramount and peripheral instances

## Impeccable Maintainability
- [x] Does the sumptuous composition of file structure adhere to a rigorous and undeviating pattern? (ports and adapters are exemplary)
- [x] Do the divine names of files, functions, variables, and objects represent their sublime purposes?
- [x] Is there any unwarranted connection complicating the art of refactoring or testing (e.g. unseemly linkage between email and SMS functions)?
- [x] Are the sophisticated layers of the code's concerns adequately bifurcated, if deemed necessary? E.g. API code elegantly refrains from interaction with the database
- [x] Is an illusory complexity at bay, thus ensuring an ease for reasoning upon the sacred code?
- [x] Do comments - those ethereal whispers of insight - elucidate the enigmatic "why?" when undoubtedly essential
- [x] Are the monumental trifecta of API, architecture, setup, and usage adeptly documented (e.g. an erudite README and OpenAPI) for future reverence?
- [x] Do the scintillating elements of code allow for masterful configuration sans the laborious toil of refactoring?

## Exemplary Security & Privacy
- [x] Are there opportunities for nefarious malfeasance that bear scrutiny? E.g. copious requests of herculean volume? Unsavory input of an insidious design?
- [x] Are all gateways to knowledge and data treated with the utmost authentication and authorization?
- [x] Does any process, resource, or humble user wield access beyond their realm of necessity?
- [x] Is all PII and data of a delicate nature treated with care - unlogged, encrypted, and withheld from check-in processes?
- [x] Have third-party dependencies received their due diligence, vetted, and properly affixed in place?

## Unyielding Robustness
- [x] Can you, in your esteemed position, conjure up errors or conditions that would lead our software into the dark abyss of unpredictability?
- [x] Are all statements endowed with a voracious appetite for scale, able to consume and transform vast data sets?
- [x] Are all factors with potential impact on system load, service limitations, and the burdens of cost adequately accounted for?
- [x] Do the divine logs showcase the triumphs and tribulations of read/write operations, as an aid for eager debugging and support?
- [x] Are error messages fashioned to be both reader-friendly and insightful, revealing the key yet non-sensitive details that unravel the mysteries of debugging and support?

**Comment by t04glovern** [comment]
Oh nooo, senpai~! This isn't looking too peachy, is it? UwU sweats nervously

### Unquestionable Testability

- [ ] OwO, can we even dream of our tests doing their jobby wobby? (Black-box tests are giving us such a hard time, teehee~)
- [ ] It's like we're lost in a foggy forest, isn't it? The system behavior is super duper confusing, our poor little tests can't make sense of it. pouty face
- [ ] We're juggling so many testing techniques, but none of them seem to be our knight in shining armor! (Unit + integration, more like "disunity + complication!")
- [ ] Our code coverage? Oh, it's like trying to cover an elephant with a teeny weeny blanket! We're missing out on all the important stuffies. >.<

### Impeccable Maintainability
- [ ] Is our file structure even a little bit organized? It's like a room full of clutter after a pillow fight! (Ports and adapters? More like "ports and disasters" teehee!)
- [ ] The namesies of our files, functions, variables, and objects are like an alien language, they're so hard to understand, uguu~
- [ ] Refactoring and testing feel like we're stuck in a knotty problem, like untangling a huge ball of yarn. Everything's mixed up! cries
- [ ] Our API code is like a busybody, always messing around with the database's private stuff. Can't it stay in its own lane? pouts
- [ ] Reasoning with our code is like talking to a grumpy old cat. It's sooooo complicated! UwU
- [ ] Our comments? They're like riddles wrapped in enigmas. Why can't they be straightforward and helpful? whimpers
- [ ] Our big, fancy README and OpenAPI are like a cipher text. Can anyone even decipher what they're saying? cries in uWu
- [ ] Our code is a stubborn little pouty-pants, refusing to change without a big fuss. sigh

### Exemplary Security & Privacy

- [ ] It's like we're inviting all sorts of baddies in! Can we even handle big scary requests? And what about those mischievous inputs trying to sneak past us?
- [ ] We're practically handing out VIP passes to our castle! Do we even know who's allowed where? worries
- [ ] Everyone seems to have a master key! It's like we're sharing all our secrets without a care! nervous giggles
- [ ] Our PII and data are supposed to be our treasures, but it's like we're leaving them in the open. We need to protect our precious stuff! cries
- [ ] Third-party dependencies? It's like we're trusting strangers without even checking if they're good or bad first. shivers

### Unyielding Robustness

- [ ] We're practically inviting all sorts of boo-boos to happen! Can we even handle errors without our world turning upside down?
- [ ] All our statements are like cute little bunnies trying to lift heavy weights. Can they even handle all the data we're throwing at them? worries
- [ ] It's like we're playing hide and seek with potential problems. Are we even prepared for system load, service limitations, or the big bad costs? pouty face
- [ ] Our logs? They're like a bedtime story that doesn't make any sense. How are we supposed to debug or support with that? UwU
- [ ] Our error messages? They're like cryptic messages in a bottle. How are we supposed to fix things if we don't know what's wrong? cries in uWu

**Pull request closed without merging**
